export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const FETCH_DASHBOARD_INFO = "FETCH_DASHBOARD_INFO";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const UPDATE_IMAGE = "UPDATE_IMAGE";
export const ERROR_STATE = "ERROR_STATE";
