export const FETCH_TEAMS = 'FETCH_TEAMS'
export const FETCH_EVENTS = 'FETCH_EVENTS'
export const FETCH_TESTIMONIALS = 'FETCH_TESTIMONIALS'
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES'

export const ERROR_STATE = 'ERROR_STATE'
