export const INITIATE_STRIPE_PAYMENT = "INITIATE_STRIPE_PAYMENT";
export const STRIPE_PAYMENT_SUCCESS = "STRIPE_PAYMENT_SUCCESS";
export const NOTIFY_STRIPE_PAYMENT_SUCCESS = "NOTIFY_STRIPE_PAYMENT_SUCCESS";
export const NOTIFY_STRIPE_PAYMENT_FAILURE = "NOTIFY_STRIPE_PAYMENT_FAILURE";
export const STRIPE_PAYMENT_FAILURE = "STRIPE_PAYMENT_FAILURE";
export const RESET_STRIPE_PAYMENT = "RESET_STRIPE_PAYMENT";
